"""String constants for file paths, model keys, and Socket.IO events."""

TEMPLATE_ROOT = "./templates"
MODEL_GENERATION_LOCATION = TEMPLATE_ROOT + "/json-model/"
MODEL_GENERATION_TYPE = ".json"
MODEL_NAME = "model_name"
CODE_TEMPLATE_FOLDER = "code-templates/"
FILE_TARGET = "target_field"
FILE_ID = "file_id"
FILE_NAME = "file_name"
DATASET = "dataset"
LEARNING_MODEL = "dl_model"
MODEL_TRAINING_SPLIT = "training_split"
MODEL_JSON_FILE = "json_file"
MODEL_OPTIMIZER = "optimizer"
MODEL_METRIC = "metric"
MODEL_EPOCHS = "epochs"
PROBLEM_TYPE = "problem_type_id"
CODE = "code"
DL_MODEL = "dl_model"
SOCKETIO_DL_NAMESPACE = "/dl-result"
SOCKETIO_LISTENER = "result :::"
IMG_SIZE = "image_size"
BATCH_SIZE = "batch_size"
COLOR_MODE = "color_mode"
LABEL_MODE = "label_mode"

LAYER_REGISTRY_LOCATION = TEMPLATE_ROOT + "/layer_registry.json"
