"""make_training_fields_nullable

Revision ID: 2e66fba94864
Revises: a728b2d08d59
Create Date: 2026-02-23 15:21:35.108540

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e66fba94864"
down_revision = "a728b2d08d59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model_basic", "file_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("model_basic", "model_type", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("model_basic", "training_split", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.alter_column("model_basic", "optimizer", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("model_basic", "metric", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("model_basic", "epochs", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("model_basic", "loss", existing_type=sa.VARCHAR(length=50), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model_basic", "loss", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("model_basic", "epochs", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("model_basic", "metric", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("model_basic", "optimizer", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("model_basic", "training_split", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("model_basic", "model_type", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("model_basic", "file_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
