"""add_model_training_run_table

Revision ID: 9e13d23b8149
Revises: d4b7f1a03e82
Create Date: 2026-04-25 12:02:53.913344

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e13d23b8149"
down_revision = "d4b7f1a03e82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.create_table(
        "data_file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("disk_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_file_project_id"), "data_file", ["project_id"], unique=False)
    op.create_table(
        "data_process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["data_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_process_file_id"), "data_process", ["file_id"], unique=False)
    op.create_table(
        "image_properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_size", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("color_mode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("label_mode", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
        sa.CheckConstraint("color_mode IN ('grayscale', 'rgb', 'rgba')", name="color_mode_check"),
        sa.CheckConstraint("label_mode IN ('int', 'categorical', 'binary')", name="label_mode_check"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["data_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_basic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("model_type", sa.Integer(), nullable=True),
        sa.Column("target_field", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("training_split", sa.Float(), nullable=True),
        sa.Column("optimizer", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("metric", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("epochs", sa.Integer(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("loss", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("graph_json", sa.JSON(), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["data_file.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name"),
    )
    op.create_index(op.f("ix_model_basic_file_id"), "model_basic", ["file_id"], unique=False)
    op.create_index(op.f("ix_model_basic_project_id"), "model_basic", ["project_id"], unique=False)
    op.create_table(
        "model_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_basic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_configs_model_id"), "model_configs", ["model_id"], unique=False)
    op.create_table(
        "model_training_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("epochs_configured", sa.Integer(), nullable=True),
        sa.Column("batch_size_configured", sa.Integer(), nullable=True),
        sa.Column("training_split_configured", sa.Float(), nullable=True),
        sa.Column("optimizer", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("loss_fn", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("metric_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("final_train_loss", sa.Float(), nullable=True),
        sa.Column("final_train_metric", sa.Float(), nullable=True),
        sa.Column("final_val_loss", sa.Float(), nullable=True),
        sa.Column("final_val_metric", sa.Float(), nullable=True),
        sa.Column("epoch_losses", sa.JSON(), nullable=True),
        sa.Column("epoch_metrics", sa.JSON(), nullable=True),
        sa.Column("epoch_val_losses", sa.JSON(), nullable=True),
        sa.Column("epoch_val_metrics", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["model_basic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_training_run_model_id"), "model_training_run", ["model_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_training_run_model_id"), table_name="model_training_run")
    op.drop_table("model_training_run")
    op.drop_index(op.f("ix_model_configs_model_id"), table_name="model_configs")
    op.drop_table("model_configs")
    op.drop_index(op.f("ix_model_basic_project_id"), table_name="model_basic")
    op.drop_index(op.f("ix_model_basic_file_id"), table_name="model_basic")
    op.drop_table("model_basic")
    op.drop_table("image_properties")
    op.drop_index(op.f("ix_data_process_file_id"), table_name="data_process")
    op.drop_table("data_process")
    op.drop_index(op.f("ix_data_file_project_id"), table_name="data_file")
    op.drop_table("data_file")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
