"""add_project_table_and_foreign_keys

Revision ID: b8d925d66e78
Revises: dc5975d9998c
Create Date: 2026-02-22 10:31:22.682022

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8d925d66e78"
down_revision = "dc5975d9998c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.add_column("data_file", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_data_file_project_id"), "data_file", ["project_id"], unique=False)
    op.create_foreign_key(None, "data_file", "project", ["project_id"], ["id"])
    op.alter_column("data_process", "file_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_data_process_file_id"), "data_process", ["file_id"], unique=False)
    op.add_column("model_basic", sa.Column("project_id", sa.Integer(), nullable=True))
    op.alter_column("model_basic", "file_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_model_basic_file_id"), "model_basic", ["file_id"], unique=False)
    op.create_index(op.f("ix_model_basic_project_id"), "model_basic", ["project_id"], unique=False)
    op.create_foreign_key(None, "model_basic", "project", ["project_id"], ["id"])
    op.alter_column("model_configs", "model_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_model_configs_model_id"), "model_configs", ["model_id"], unique=False)
    op.add_column("model_results", sa.Column("epoch", sa.Integer(), nullable=False))
    op.alter_column("model_results", "model_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_model_results_model_id"), "model_results", ["model_id"], unique=False)
    op.drop_column("model_results", "epoc")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_results", sa.Column("epoc", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_model_results_model_id"), table_name="model_results")
    op.alter_column("model_results", "model_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("model_results", "epoch")
    op.drop_index(op.f("ix_model_configs_model_id"), table_name="model_configs")
    op.alter_column("model_configs", "model_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "model_basic", type_="foreignkey")
    op.drop_index(op.f("ix_model_basic_project_id"), table_name="model_basic")
    op.drop_index(op.f("ix_model_basic_file_id"), table_name="model_basic")
    op.alter_column("model_basic", "file_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("model_basic", "project_id")
    op.drop_index(op.f("ix_data_process_file_id"), table_name="data_process")
    op.alter_column("data_process", "file_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "data_file", type_="foreignkey")
    op.drop_index(op.f("ix_data_file_project_id"), table_name="data_file")
    op.drop_column("data_file", "project_id")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
