"""empty message

Revision ID: 36e0306ca86f
Revises: d03f041a77fd
Create Date: 2024-03-13 02:07:43.037082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e0306ca86f'
down_revision = 'd03f041a77fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_basic', sa.Column('loss', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_basic', 'loss')
    # ### end Alembic commands ###
