"""empty message

Revision ID: cb58c1cf5202
Revises: 97f713b19cb0
Create Date: 2024-08-11 19:15:45.719791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb58c1cf5202'
down_revision = '97f713b19cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('color_mode', sa.String(length=10), nullable=False),
    sa.Column('label_mode', sa.String(length=15), nullable=False),
    sa.CheckConstraint("color_mode IN ('grayscale', 'rgb', 'rgba')", name='color_mode_check'),
    sa.CheckConstraint("label_mode IN ('int', 'categorical', 'binary')", name='label_mode_check'),
    sa.ForeignKeyConstraint(['id'], ['data_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_properties')
    # ### end Alembic commands ###
